services:
    todo_list_api:
        build:
            context: ..
            dockerfile: TodoListApp.Api/Dockerfile
        ports:
            - "8080:8080"
        container_name: TodoListAppApi
        depends_on:
            - database
    databasetodolist:
        image: postgres:latest
        ports:
            - "5432:5432"
        environment:
            user: postgres
            password: 1234
        volumes:
            - db_data:/var/lib/postgresql/data
volumes:
    db_data:
    