services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
        POSTGRES_DB: TodoListDb
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 1234
    ports:
        - 5433:5432
    volumes:
        - postgres-data:/var/lib/postgresql/data

volumes:
     postgres-data: